### ISSUE TITLE
Cache clear method

### ISSUE THREAD

**Issue by Bordovsky** [modpreneur/trinity-settings#1]
make comfortable cache clear method in manager

```
    if ($this->cacheProvider) {
        $this->cacheProvider->deleteAll();
    }
```

or even if name delete just the one. 
or fix method clear in manager to delete all when nothing is passed?

**Comment by jjanekk** [comment]
https://github.com/modpreneur/trinity-settings/blob/master/Manager/SettingsManager.php#L227
